# Generated by Django 5.0.1 on 2024-01-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_value', models.CharField(max_length=255)),
                ('sum_assured', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.IntegerField()),
                ('term', models.IntegerField()),
                ('calculated_premium', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
