# Generated by Django 5.0.1 on 2024-01-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumcalculation',
            name='age',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='premiumcalculation',
            name='calculated_premium',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='premiumcalculation',
            name='sum_assured',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='premiumcalculation',
            name='term',
            field=models.CharField(max_length=255),
        ),
    ]
